ACCESS_TOKEN: "EAAO3i2rOs5EBO0vfBY5ODwZAOnrLJoibZBTptb5uZAfZBi5NMJ8CNTwcOLCWiEmNURIWA1hrtmpM6fbDcBPVpDXqcWbPEOkgk5fQhu46M8g6gxpjPHkFyly5lUQRw7ZAJUaklx1zmSo47f13Jys5ThkmnmfyGGlWHhJPVHNRZCbtjZCPkn1hfS7BeyxfyE4T3f7ELKzskLhKLUBMIurMzC57K3jgmEZD"

APP_ID: "1046234350400401"

APP_SECRET: "3809c72b9ebfaae5aba5c3e69e9eec80"

RECIPIENT_WAID: "+5561984168896"

PHONE_NUMBER_ID: "357875687418333"

VERSION: "v18.0"

VERIFICATION_TOKEN: "1234"