ACCESS_TOKEN: "EAAO3i2rOs5EBO2DXcWrKa375kAWZAhZBfXT7IdFP7XOC5gRAMgo7AaXl2TTZCwCteZCCyZCRPHOcO1pzX7yhZBPnzpibEmLW9W4JZBsfoCIGyKYpcVDPEdKWQwMvYojo9ZC30MgqHLyYlmZAn5Ba8APr6aoE3y1BUBxNrWvpYbJzwfxXaKFs4E6mQ6TrliPoA7CfNUChkzH9iEmGltVe2oU0ZD"

APP_ID: "1046234350400401"

APP_SECRET: "3809c72b9ebfaae5aba5c3e69e9eec80"

RECIPIENTWAID: "+5561984168896"

PHONE_NUMBER_ID: "357875687418333"

VERSION: "v18.0"

VERIFICATION_TOKEN: "1234"